name = "siliconflow-transcribe"
account_id = "xxx"
compatibility_date = "2025-06-18"
pages_build_output_dir = "./public"

[vars]
VERIFY_TOKENS        = "alpha123,beta456,gamma789"
SILICONFLOW_API_KEYS = "sk-xxx"


[env.production]